### ISSUE TITLE
Complimenti per il bel lavoro :)

### ISSUE THREAD

**Issue by cortinico** [DangerBlack/SNA-on-Game-of-Thrones#1]
Ho dato un'occhiata veloce, complimenti per l'ottimo lavoro. Fa parte di un esame?
Nic

**Comment by DangerBlack** [comment]
Si sto facendo un esame, al momento é ancora in una fase un pò fresca.
Ma spero di tirare fuori qualcosa di interessante!
Grazie Nicola!
Daniele

--- Messaggio originale ---

Da: "Nicola Corti" notifications@github.com
Inviata: 02 febbraio 2015 23:02
A: "DangerBlack/SNA-on-Game-of-Thrones" SNA-on-Game-of-Thrones@noreply.github.com
Oggetto: [SNA-on-Game-of-Thrones] Complimenti per il bel lavoro :) (#1)

Ho dato un'occhiata veloce, complimenti per l'ottimo lavoro. Fa parte di un esame?
Nic

---

Reply to this email directly or view it on GitHub:
https://github.com/DangerBlack/SNA-on-Game-of-Thrones/issues/1
